apiVersion: v1
kind: Secret
metadata:
  name: vdt-db-env
  namespace: vdt-final
type: opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongo_user
  MONGO_INITDB_ROOT_PASSWORD: mongo_password
  MONGO_INITDB_DATABASE: vdt-final
