apiVersion: v1
kind: ConfigMap
metadata:
  name: vdt-db-config
  namespace: vdt-final
data:
  mongod.conf: |
    storage:
      dbPath: /data/db
    net:
      bindIp: 0.0.0.0
    replication:
      replSetName: "rs0"
